blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/AstraGuardian/Media_Duplicate_Detector/discussions
    about: Ask questions and discuss ideas with the community
